apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxypass.fullname" . }}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  _;
          location / {
            proxy_ssl_verify off;
            proxy_set_header Host external-udp.xn--ensea-rta.cl;
            proxy_pass {{ .Values.Proxy.URL }};
        }
      }
    }
